// <auto-generated>
// ReSharper disable RedundantUsingDirective
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable RedundantNameQualifier
// TargetFrameworkVersion = 4.52
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Data.Entity.Infrastructure;
using System.Linq.Expressions;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity;
using System.Data;
using System.Data.Entity.Core.Objects;
using System.Data.SqlClient;
using System.Data.SqlTypes;
using System.Data.Entity.ModelConfiguration;
using System.Threading;
using DatabaseGeneratedOption = System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption;

namespace LibraryTAL.Data.Designer
{
    // Players
    [GeneratedCodeAttribute("EF.Reverse.POCO.Generator", "2.17.1.0")]
    public partial class Player
    {
        public Guid PlayerId { get; set; } // PlayerID (Primary key)
        public Guid? RegistrationId { get; set; } // RegistrationID
        public Guid? TeamId { get; set; } // TeamID
        public Guid? EventId { get; set; } // EventID
        public Guid? CrewId { get; set; } // CrewID

        // Reverse navigation
        public virtual ICollection<Manch> Manches { get; set; } // Manches.FK__Manches__PlayerI__1A69E950
        public virtual ICollection<Player> Players { get; set; } // Players.FK__Players__CrewID__1975C517

        // Foreign keys
        public virtual Event Event { get; set; } // FK__Players__EventID__1881A0DE
        public virtual Player Player_CrewId { get; set; } // FK__Players__CrewID__1975C517
        public virtual Registration Registration { get; set; } // FK__Players__Registr__1699586C
        public virtual Team Team { get; set; } // FK__Players__TeamID__178D7CA5
        
        public Player()
        {
            Manches = new List<Manch>();
            Players = new List<Player>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
