// <auto-generated>
// ReSharper disable RedundantUsingDirective
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable RedundantNameQualifier
// TargetFrameworkVersion = 4.52
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Data.Entity.Infrastructure;
using System.Linq.Expressions;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity;
using System.Data;
using System.Data.Entity.Core.Objects;
using System.Data.SqlClient;
using System.Data.SqlTypes;
using System.Data.Entity.ModelConfiguration;
using System.Threading;
using DatabaseGeneratedOption = System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption;

namespace LibraryTAL.Data.Designer
{
    // Races
    [GeneratedCodeAttribute("EF.Reverse.POCO.Generator", "2.17.1.0")]
    public partial class Race
    {
        public Guid RaceId { get; set; } // RaceID (Primary key)
        public string Code { get; set; } // Code
        public string Description { get; set; } // Description
        public float Lenght { get; set; } // Lenght
        public float Slope { get; set; } // Slope
        public float Width { get; set; } // Width
        public string StartAddress { get; set; } // StartAddress
        public string EndAddress { get; set; } // EndAddress
        public DateTime Date { get; set; } // Date
        public string Place { get; set; } // Place
        public string EntrantNumber { get; set; } // EntrantNumber
        public double SubscriptionPrice { get; set; } // SubscriptionPrice
        public DateTime PaymentDate { get; set; } // PaymentDate
        public string PaymentPlace { get; set; } // PaymentPlace
        public string OrganizedBy { get; set; } // OrganizedBy
        public byte[] Photo { get; set; } // Photo
        public string Pavement { get; set; } // Pavement

        // Reverse navigation
        public virtual ICollection<Event> Events { get; set; } // Events.FK__Events__RaceID__2022C2A6
        public virtual ICollection<Registration> Registrations { get; set; } // Registrations.FK__Registrat__RaceI__15A53433
        
        public Race()
        {
            Events = new List<Event>();
            Registrations = new List<Registration>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
