// <auto-generated>
// ReSharper disable RedundantUsingDirective
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable RedundantNameQualifier
// TargetFrameworkVersion = 4.52
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Data.Entity.Infrastructure;
using System.Linq.Expressions;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity;
using System.Data;
using System.Data.Entity.Core.Objects;
using System.Data.SqlClient;
using System.Data.SqlTypes;
using System.Data.Entity.ModelConfiguration;
using System.Threading;
using DatabaseGeneratedOption = System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption;

namespace LibraryTAL.Data.Designer
{
    // Scores
    public partial class ScoreConfiguration : EntityTypeConfiguration<Score>
    {
        public ScoreConfiguration()
            : this("dbo")
        {
        }
 
        public ScoreConfiguration(string schema)
        {
            ToTable(schema + ".Scores");
            HasKey(x => x.ScoreId);

            Property(x => x.ScoreId).HasColumnName("ScoreID").IsRequired().HasColumnType("uniqueidentifier").HasDatabaseGeneratedOption(DatabaseGeneratedOption.None);
            Property(x => x.Ranking).HasColumnName("Ranking").IsRequired().HasColumnType("int");
            Property(x => x.ChampionshipId).HasColumnName("ChampionshipID").IsOptional().HasColumnType("uniqueidentifier");
            Property(x => x.PointId).HasColumnName("PointID").IsOptional().HasColumnType("uniqueidentifier");
            Property(x => x.SeasonId).HasColumnName("SeasonID").IsOptional().HasColumnType("uniqueidentifier");

            // Foreign keys
            HasOptional(a => a.Championship).WithMany(b => b.Scores).HasForeignKey(c => c.ChampionshipId); // FK__Scores__Champion__22FF2F51
            HasOptional(a => a.Point).WithMany(b => b.Scores).HasForeignKey(c => c.PointId); // FK__Scores__PointID__23F3538A
            HasOptional(a => a.Season).WithMany(b => b.Scores).HasForeignKey(c => c.SeasonId); // FK__Scores__SeasonID__24E777C3
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
